# Site settings
title: Mez Pahlan
email: mez.pahlan@gmail.com
url: https://mezpahlan.github.io
description: 'I am a Web &amp; Mobile developer with a passion for Mobile technologies, Agile, DevOps, Continuous Integration, Open Source, Front End Development, and Visual Design.'

# Blog post settings
excerpt_separator: <!-- more -->
paginate: 10
paginate_path: '/blog/page:num/'
future: true

# Collection settings
collections:
  - portfolio

# Default front matter
defaults:
  -
    scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'blog'
      author: 'Mez Pahlan'
      category: 'blog'
      comments: true

# Colour settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Mez Pahlan

# Contact settings
contact:
  location: Location
  social: Around the Web
  credits: About Mez

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: https://www.google.com/+MezPahlan
  - title: twitter
    url: https://twitter.com/mezpahlan
  - title: linkedin
    url: https://www.linkedin.com/in/mezpahlan
  - title: github-alt
    url: https://github.com/mezpahlan

# Postal address (add as many lines as necessary)
address:
  - line: Bristol
  - line: UK

# Credits content
credits: 'I am a Web &amp; Mobile developer with a passion to develop code and have fun doing it!'

# Build settings
exclude: [Rakefile, Gemfile, Gemfile.lock, WORKFLOW]
include: [.nojekyll]
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Jekyll Responsive Image settings
responsive_image:
  template: _includes/common/responsive-image.html
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
  base_path: assets/images/_fullsize
  output_path_format: assets/images/%{dirname}/%{filename}-%{width}x%{height}.%{extension}

# Jekyll Archive settings
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive
  permalinks:
    tag: '/blog/tag/:name/'
