# Site settings
title: Mez Says
tagline: 'Bits and bobs that I get up to'
description: 'Android Developer based in Bristol, UK. Bits and bobs that I get up to.'
email: mez.pahlan@gmail.com
url: https://mezpahlan.github.io
baseurl: # the optional subpath of your site, e.g. "/blog"
         # NB: This applies to all pages in your Jekyll site.
         # If you want to move just the blog index pages but keep
         # other pages at root, see the paginate_path and
         # sidebar_blog_link below.
theme: jekyll-theme-hydeout

# Blog post settings
excerpt_separator: <!-- more -->

# Default front matter
# defaults:
#   -
#     scope:
#       path: '_posts'
#       type: 'posts'
#     values:
#       layout: 'blog'
#       author: 'Mez Pahlan'
#       category: 'blog'
#       comments: true

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: https://www.google.com/+MezPahlan
    icon: google-plus.svg
  - title: twitter
    url: https://twitter.com/mezpahlan
    icon: twitter.svg
  - title: linkedin
    url: https://www.linkedin.com/in/mezpahlan
    icon: linkedin.svg
  - title: github
    url: https://github.com/mezpahlan
    icon: github.svg

# Build settings
exclude: [Rakefile, Gemfile, Gemfile.lock, WORKFLOW]
include: [.nojekyll]
permalink: pretty
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: '/page:num' # Or '/blog/page:num' if you want to move your index pages
future: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-responsive-image

# Custom vars
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
disqus:
  shortname: mezpahlan

# Jekyll Responsive Image settings
responsive_image:
  template: _includes/common/responsive-image.html
  sizes:
    - width: 100
      quality: 100
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
  auto_rotate: true
  base_path: _fullsize
  output_path_format: assets/images/%{dirname}/%{filename}-%{width}x%{height}.%{extension}
