baseURL = "https://mezpahlan.github.io/"
disablePathToLower = true
languageCode = "en-gb"
title = "Mez Says"
theme = "hyde"
paginate = 7
disqusShortname = "mezpahlan"
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
rssLimit = 10

[author]
  name = 'Mez Pahlan'

[params]
  description = "Android Developer based in Bristol, UK. Bits and bobs that I get up to."

[menus]
  main = [
      { Weight = 4, Name = "mastodon", URL = "https://androiddev.social/@mez" },
      { Weight = 5, Name = "twitter", URL = "https://twitter.com/mezpahlan" },
      { Weight = 6, Name = "linkedin", URL = "https://www.linkedin.com/in/mezpahlan" },
      { Weight = 7, Name = "github", URL = "https://github.com/mezpahlan" }
  ]